all:
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 01_demo.c -L../diag_master_api -ldm_api -o 01_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 02_demo.c -L../diag_master_api -ldm_api -o 02_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 03_demo.c -L../diag_master_api -ldm_api -o 03_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 04_demo.c -L../diag_master_api -ldm_api -o 04_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 05_demo.c -L../diag_master_api -ldm_api -o 05_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 06_demo.c -L../diag_master_api -ldm_api -o 06_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 07_demo.c -L../diag_master_api -ldm_api -o 07_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 08_demo.c -L../diag_master_api -ldm_api -o 08_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 09_demo.c -L../diag_master_api -ldm_api -o 09_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 10_demo.c -L../diag_master_api -ldm_api -o 10_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 11_demo.c -L../diag_master_api -ldm_api -o 11_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 12_demo.c -L../diag_master_api -ldm_api -o 12_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 13_demo.c -L../diag_master_api -ldm_api -o 13_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 14_demo.c -L../diag_master_api -ldm_api -o 14_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 15_demo.c -L../diag_master_api -ldm_api -o 15_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 16_demo.c -L../diag_master_api -ldm_api -o 16_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 17_demo.c -L../diag_master_api -ldm_api -o 17_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 18_demo.c -L../diag_master_api -ldm_api -o 18_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 19_demo.c -L../diag_master_api -ldm_api -o 19_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 20_demo.c -L../diag_master_api -ldm_api -o 20_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 21_demo.c -L../diag_master_api -ldm_api -o 21_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 22_demo.c -L../diag_master_api -ldm_api -o 22_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 23_demo.c -L../diag_master_api -ldm_api -o 23_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 24_demo.c -L../diag_master_api -ldm_api -o 24_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 25_demo.c -L../diag_master_api -ldm_api -o 25_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 26_demo.c -L../diag_master_api -ldm_api -o 26_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ 27_demo.c -L../diag_master_api -ldm_api -o 27_demo
	gcc -I ../diag_master_api/ -I ../diag_master_common/ api_test.c -L../diag_master_api -ldm_api -o api_test
clean:
	rm 01_demo
	rm 02_demo
	rm 03_demo
	rm 04_demo
	rm 05_demo
	rm 06_demo
	rm 07_demo
	rm 08_demo
	rm 09_demo
	rm 10_demo
	rm 11_demo
	rm 12_demo
	rm 13_demo
	rm 14_demo
	rm 15_demo
	rm 17_demo
	rm 18_demo
	rm 19_demo
	rm 20_demo
	rm 21_demo
	rm 22_demo
	rm 23_demo
	rm 24_demo
	rm 25_demo
	rm 26_demo
	rm 27_demo
	rm api_test














